# Generated by Django 3.2.6 on 2021-08-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd',
            old_name='connect',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='bd',
            old_name='tile',
            new_name='title',
        ),
    ]
